import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/widgets.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

import '../../firebase_options.dart';
import '../config/env.dart';
import '../messaging/fcm_background_handler.dart';

/// Boots the app, optionally inside a Sentry zone.
///
/// If [AppEnv.sentryDsn] is empty (e.g. local dev), Sentry is skipped and the
/// app runs normally. See the architecture doc §6/§17.
Future<void> bootstrap({
  required AppEnv env,
  required Widget Function() builder,
}) async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options generated by FlutterFire CLI.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Register the FCM background/terminated message handler. Must run after
  // Firebase is initialized and before runApp so the background isolate is
  // wired from the first launch.
  registerFcmBackgroundHandler();

  if (env.sentryDsn.isEmpty) {
    runApp(builder());
    return;
  }

  await SentryFlutter.init((options) {
    options.dsn = env.sentryDsn;
    options.environment = env.flavor.name;
    options.tracesSampleRate = env.isProd ? 0.2 : 1.0;
  }, appRunner: () => runApp(builder()));
}
